# Generated by Django 4.2.6 on 2023-11-28 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_anime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_animes', to=settings.AUTH_USER_MODEL),
        ),
    ]
