# Generated by Django 4.2.6 on 2023-11-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_anime_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
