# Generated by Django 4.2.6 on 2023-11-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_anime_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='server_options',
        ),
        migrations.AddField(
            model_name='episode',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ServerOption',
        ),
    ]
