# Generated by Django 4.2.6 on 2023-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_episode_server_options_episode_video_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='epno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
