# Generated by Django 4.2.6 on 2023-11-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_episode_epno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='epno',
            new_name='episode_number',
        ),
    ]
