# Generated by Django 4.2.6 on 2023-11-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_epno_episode_episode_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_number',
        ),
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
