# Generated by Django 4.2.6 on 2023-11-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_episode_episode_number_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
