# Generated by Django 4.2.6 on 2023-12-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_comment_options_remove_event_contributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='premium',
        ),
    ]
